name: SE-Scaler gRPC Request
description: 'A GitHub Action to request scaling of a service using gRPC'
inputs:
    region:
        required: true
        description: 'Region: Where the scale request will be executed'
    cloud_type:
        required: true
        description: 'Cloud Type: The cloud provider to use for scaling'
    replicas:
        required: true
        description: 'Replicas: Number of replicas to scale to'

runs:
    using: 'composite'
    steps:
    - name: Report input Data
      id: report_input_data
      shell: bash
      run: |
        {
            echo "## SE-Scaler Github Action: "
            echo "Requested initiated by ${{ github.actor }}!"
            echo ""
            echo " We're aiming to scale with the following data:"
            echo "| Input            | Value                           |"
            echo "|------------------|---------------------------------|"
            echo "| Region           | ${{ inputs.region }} |"
            echo "| Cloud Type       | ${{ inputs.cloud_type }} |"
            echo "| # of Replicas    | ${{ inputs.replicas }} |"
        }