name: Finish approval
on:
  workflow_run:
    workflows: ["Start approval"]
    types:
      - completed

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4
            - name: Finish Approval
              run: echo "Approval for greeting has been completed"
            - name: Greet the person
              run: echo "Hello, ${{ github.event.workflow_run.conclusion }}!"