name: SE Scaler - Scale Request
run-name: ${{ github.actor }} has requested a scale operation on SE-Server
on:
    workflow_dispatch:
        inputs:
            region:
                description: 'Region: Where the scale request will be exeuted'
                required: true
                type: choice
                options:
                    - 'US - United States'
                    - 'EU - Europe'
                    - 'AP - Asia Pacific'
                    - 'CA - Canada'
            cloud_type:
                description: 'Cloud Type: The cloud provider to use for scaling'
                required: true
                type: choice
                options:
                    - 'Q - Partner'
                    - 'P - Production'
                    - 'T - Development'
            replicas:
                description: 'Replicas: Number of replicas to scale to'
                required: true
                type: number
            name: 
                description: 'Name of the person to greet'
                required: true
                default: 'GitHub'

jobs:
    display_input_data:
        runs-on: ubuntu-latest
        steps:
        - name: Report input Data
          id: report_input_data
          shell: bash
          run: |
            {
                echo "## SE-Scaler Github Action: "
                echo "Requested initiatied by ${{ github.actor }}!"
                echo ""
                echo " We're aiming to scale with the following data:"
                echo "| Input            | Value                           |"
                echo "|------------------|---------------------------------|"
                echo "| Region           | ${{ github.event.inputs.region }} |"
                echo "| Cloud Type       | ${{ github.event.inputs.cloud_type }} |"
                echo "| # of Replicas    | ${{ github.event.inputs.replicas }} |"
                echo "| Name             | ${{ github.event.inputs.name }} |"
            }
    
    request-approvals:
        needs: display_input_data
        environment: production
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Request Approvals
              run: echo "Requesting approvals from Managers"
    
    finish-approval:
        needs: request-approvals
        runs-on: ubuntu-latest
        steps:
          - name: Finished Approval
            shell: bash
            run: | 
                {
                  echo "Approval status: Approved 🟢"
                }
    
    request-scale:
        needs: finish-approval
        runs-on: ubuntu-latest
        steps:
            - name: Scale SE-Server
              run: |
                {
                    echo "Scaling SE-Server to ${{ github.event.inputs.replicas }} replicas"
                    echo "http://eks-trunk-private-${{ github.event.inputs.region }}.internal.${{ github.event.inputs.cloud_type }}.com/se-scaler"
                }