name: SE-Scale GH Action Demo
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name of the person to greet'
                required: true
                default: 'GitHub'

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4
            - name: List files in the repository
              run: |
                  ls ${{ github.workspace }}
            - name: Request Approval
              run: echo "Requesting approval for greeting"