name: Start approval
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name of the person to greet'
                required: true
                default: 'GitHub'

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production  # Reference the environment here
        outputs:
            name: ${{ steps.set-output.outputs.name }}
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4
            - name: List files in the repository
              run: |
                  ls ${{ github.workspace }}
            - name: Set output
              id: set-output
              run: echo "::set-output name=name::${{ github.event.inputs.name }}"
            - name: Request Approval
              run: echo "Requesting approval for greeting"