name: SE-Scaler
run-name: 'SE-Scaler: Requested to scale in ${{ inputs.region }}'
permissions:
  contents: read
  deployments: read
  id-token: write
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Region: Where the scale will be executed'
        required: true
        type: choice
        options:
          - ust1
          - usp1
          - eup1
          - cap1
          - app1
          - usq1
          - euq1
          - caq1
      replicas:
        description: 'Replicas: Pods to scale to'
        default: '1'
        required: true
        type: number
      timeout:
        description: 'Timeout: Request will be cancelled in the specified seconds if not succeeded'
        default: '60'
        required: true
        type: number

jobs:
  display_input_data:
    runs-on: ubuntu-latest
    steps:
      - name: Report input Data
        id: report_input_data
        shell: bash
        run: |
          {
              echo "## SE-Scaler requested initiated by ${{ github.actor }}!"
              echo "--------------------------------------------------------------------"
              echo " We're aiming to scale with the following data:"
              echo "| Input            | Value                           |"
              echo "|------------------|---------------------------------|"
              echo "| Region           | ${{ github.event.inputs.region }} |"
              echo "| Replicas         | ${{ github.event.inputs.replicas }} |"
              echo "| Timeout          | ${{ github.event.inputs.timeout }} seconds |"
          }

  request-approvals:
    needs: display_input_data
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Request Approvals
        run: echo "Requesting approvals from Managers"

  finish-approval:
    needs: request-approvals
    runs-on: ubuntu-latest
    steps:
      - name: Finished Approval
        shell: bash
        run: |
          {
            echo "Approval status: Approved"
            echo "If you're seeing this, it means your request has been approved"
          }

      - name: Greet the person
        shell: bash
        run: |
          {
              echo "|------------------|---------------------------------|"
              echo "| Region           | ${{ github.event.inputs.region }} |"
              echo "| Replicas         | ${{ github.event.inputs.replicas }} |"
              echo "| Timeout          | ${{ github.event.inputs.timeout }} seconds |"
          }
